# Generated by Django 4.1.2 on 2022-10-07 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(max_length=1000)),
                ('date_begin', models.DateField()),
                ('date_end', models.DateField()),
                ('state', models.CharField(choices=[('EC', 'En Cours'), ('AT', 'Attente'), ('FN', 'Fini'), ('AB', 'Abandonne')], max_length=5)),
            ],
        ),
    ]
